DEFAULT_PAIRS = ["BTC/USD", "ETH/USD", "SOL/USD"]
DEFAULT_INTERVAL = "1h"
DEFAULT_KRAKEN_INTERVAL = "60"
DEFAULT_POLL_SECONDS = 60
DEFAULT_INITIAL_CAPITAL = 1000.0
DEFAULT_KRAKEN_COMMAND = "kraken"

MIN_CONFIDENCE = 60
SPREAD_THRESHOLD_PCT = 0.15
STOP_LOSS_PCT = 0.02
TAKE_PROFIT_PCT = 0.04
RISK_PER_TRADE = 0.05

KRAKEN_RETRIES = 3
KRAKEN_TIMEOUT_SECONDS = 30
KRAKEN_BACKOFF_SECONDS = 1.0

SIGNALS_LOG = "signals.log"
TRADES_LOG = "trades.log"
