DEFAULT_PAIRS = ["BTC/USD", "ETH/USD", "SOL/USD"]
DEFAULT_INTERVAL = "1h"
DEFAULT_KRAKEN_INTERVAL = "60"
DEFAULT_POLL_SECONDS = 60
DEFAULT_INITIAL_CAPITAL = 1000.0
DEFAULT_KRAKEN_COMMAND = "kraken"

SPREAD_THRESHOLD_PCT = 0.15
RISK_PER_TRADE = 0.05

SIGNALS_LOG = "signals.log"
TRADES_LOG = "trades.log"
